<template>
  <div class="main">
    <h1>49KEysBanger.com Privacy Policy</h1>
    <p>Effective date: Sepetember 05, 2021</p>
    <p>
      49KEysBanger.com is committed to protecting your privacy online. We are
      also committed to providing you with the very best experience we can on
      our website. In order to enhance your experience at our site we gather
      certain personal information about you that helps us customize our content
      to your tastes and preferences. Please read the following policy to
      understand how your personal information will be treated as you make full
      use of our website.
    </p>
    <p>
      This page informs you of our policies regarding the collection, use, and
      disclosure of personal data when you use our Service and the choices you
      have associated with that data.
    </p>
    <p>
      This page informs you of our policies regarding the collection, use, and
      disclosure of personal data when you use our Service and the choices you
      have associated with that data.
    </p>
    <h3>Definitions</h3>
    <h3>Personal Data</h3>
    <p>
      Personal Data means data about a living individual who can be identified
      from those data (or from those and other information either in our
      possession or likely to come into our possession).
    </p>
    <h3>Usage Data</h3>
    <p>
      Usage Data is data collected automatically either generated by the use of
      the Service or from the Service infrastructure itself (for example, the
      duration of a page visit).
    </p>
    <h3>Cookies</h3>
    <p>Cookies are small pieces of data stored on a User's device.</p>
    <h3>Data Controller</h3>
    <p>
      Data Controller means a person who (either alone or jointly or in common
      with other persons) determines the purposes for which and the manner in
      which any personal data are, or are to be, processed.
    </p>
    <p>
      For the purpose of this Privacy Policy, we are a Data Controller of your
      data.
    </p>
    <h3>Data Processor (or Service Providers)</h3>
    <p>
      Data Processor (or Service Provider) means any person (other than an
      employee of the Data Controller) who processes the data on behalf of the
      Data Controller.
    </p>
    <p>
      We may use the services of various Service Providers in order to process
      your data more effectively.
    </p>
    <h3>Data Subject</h3>
    <p>
      Data Subject is any living individual who is the subject of Personal Data.
    </p>
    <h3>User</h3>
    <p>
      The User is the individual using our Service. The User corresponds to the
      Data Subject, who is the subject of Personal Data.
    </p>
    <h3>Information Collection and Use</h3>
    <p>
      We collect several different types of information for various purposes to
      provide and improve our Service to you.
    </p>
    <h3>Types of Data Collected</h3>
    <h3>Personal Data</h3>
    <p>
      While using our Service, we may ask you to provide us with certain
      personally identifiable information that can be used to contact or
      identify you ("Personal Data"). Personally identifiable information may
      include, but is not limited to:
    </p>
    <ul>
      <li>Email address</li>
      <li>First name and last name</li>
      <li>Phone number</li>
      <li>Address, State, Province, ZIP/Postal code, City</li>
      <li>Cookies and Usage Data</li>
    </ul>
    <p>
      We may use your Personal Data to contact you with newsletters, marketing
      or promotional materials and other information that may be of interest to
      you. You may opt out of receiving any, or all, of these communications
      from us by following the unsubscribe link or instructions provided in any
      email we send or by contacting us.
    </p>
    <h3>Usage Data</h3>
    <p>
      We may also collect information that your browser sends whenever you visit
      our Service or when you access the Service by or through a mobile device
      ("Usage Data").
    </p>
    <p>
      This Usage Data may include information such as your computer's Internet
      Protocol address (e.g. IP address), browser type, browser version, the
      pages of our Service that you visit, the time and date of your visit, the
      time spent on those pages, unique device identifiers and other diagnostic
      data.
    </p>
    <p>
      When you access the Service by or through a mobile device, this Usage Data
      may include information such as the type of mobile device you use, your
      mobile device unique ID, the IP address of your mobile device, your mobile
      operating system, the type of mobile Internet browser you use, unique
      device identifiers and other diagnostic data.
    </p>
    <h3>Location Data</h3>
    <p>
      We may use and store information about your location if you give us
      permission to do so ("Location Data"). We use this data to provide
      features of our Service, to improve and customize our Service. You can
      enable or disable location services when you use our Service at any time,
      through your device settings.
    </p>
    <h3>Tracking Cookies Data</h3>
    <p>
      We use cookies and similar tracking technologies to track the activity on
      our Service and hold certain information. Cookies are files with small
      amount of data which may include an anonymous unique identifier. Cookies
      are sent to your browser from a website and stored on your device.
      Tracking technologies also used are beacons, tags, and scripts to collect
      and track information and to improve and analyze our Service. You can
      instruct your browser to refuse all cookies or to indicate when a cookie
      is being sent. However, if you do not accept cookies, you may not be able
      to use some portions of our Service.
    </p>
    <ul>
      <li>Session Cookies. We use Session Cookies to operate our Service.</li>
      <li>
        Preference Cookies. We use Preference Cookies to remember your
        preferences and various settings.
      </li>
      <li>Security Cookies. We use Security Cookies for security purposes.</li>
    </ul>
    <h3>Use of Data</h3>
    <p>
      Our primary goal in collecting personal information is to provide you, the
      user, with a customized experience on our website. We use the collected
      data for various purposes including:
    </p>
    <ul>
      <li>To provide and maintain our Service</li>
      <li>
        To notify you about changes to our Service or updates to our website
      </li>
      <li>
        To allow you to participate in interactive features of our Service when
        you choose to do so
      </li>
      <li>To provide customer support</li>
      <li>
        To monitor the usage of our Service, estimate the size of our audience
        and measure certain traffic patterns
      </li>
      <li>To detect, prevent and address technical issues</li>
      <li>
        To provide you with news, special offers and general information about
        other goods, services and events which we offer that are similar to
        those that you have already purchased or enquired about unless you have
        opted not to receive such information
      </li>
      <li>
        To provide such capabilities as personalization services, interactive
        communications, online shopping, and personalized communication between
        you and the artists you prefer.
      </li>
      <li>
        To track the progress and number of entries in our promotions and
        contests
      </li>
      <li>To track visits to and business conducted at our online store</li>
      <li>
        To contact you on behalf of certain artists, other third parties,
        deliver targeted advertisements that may be of interest to you and
        information regarding special events at BeatStars.
      </li>
    </ul>
    <h3>Social Media</h3>
    <p>
      If you share our content through social media, for example by liking us on
      Facebook, following or tweeting about us on Twitter, or giving us a '+1'
      via Google Plus, those social networks will record that you have done so
      and may set a cookie for this purpose. In some cases, where a page on our
      website includes content from a social network, such as a Twitter feed, or
      Facebook comments box, those services may set a cookie even where you do
      not click a button. As is the case for all cookies, we cannot access those
      set by social networks, just as those social networks cannot access
      cookies we set ourselves.
    </p>
    <h3>Retention of Data</h3>
    <p>
      We will retain your Personal Data only for as long as is necessary for the
      purposes set out in this Privacy Policy. We will retain and use your
      Personal Data to the extent necessary to comply with our legal obligations
      (for example, if we are required to retain your data to comply with
      applicable laws), resolve disputes, and enforce our legal agreements and
      policies.
    </p>
    <p>
      We will also retain Usage Data for internal analysis purposes. Usage Data
      is generally retained for a shorter period of time, except when this data
      is used to strengthen the security or to improve the functionality of our
      Service, or we are legally obligated to retain this data for longer time
      periods.
    </p>
    <h3>Legal Requirements</h3>
    <p>
      49KEysBanger may disclose your Personal Data in the good faith belief that
      such action is necessary to:
    </p>
    <ul>
      <li>To comply with a legal obligation</li>
      <li>To protect and defend the rights or property of 49KEysBanger Inc.</li>
      <li></li>
      <li>
        To prevent or investigate possible wrongdoing in connection with the
        Service
      </li>
      <li>
        To protect the personal safety of users of the Service or the public
      </li>
      <li>To protect against legal liability</li>
    </ul>
    <h3>Payments</h3>
    <p>
      We may provide paid products and/or services within the Service. In that
      case, we use third-party services for payment processing (e.g. payment
      processors).
    </p>
    <p>
      We will not store or collect your payment card details. That information
      is provided directly to our third-party payment processors whose use of
      your personal information is governed by their Privacy Policy. These
      payment processors adhere to the standards set by PCI-DSS as managed by
      the PCI Security Standards Council, which is a joint effort of brands like
      Visa, Mastercard, American Express and Discover. PCI-DSS requirements help
      ensure the secure handling of payment information.
    </p>
    <p>The payment processors we work with are:</p>
    <h3>PayPal or Braintree</h3>
    <a href="https://stripe.com/us/privacy"
      >Their Privacy Policy can be viewed at</a
    >
  </div>
</template>
<style scoped>
.main {
  margin: 3% 5% 3% 5%;
}
</style>
<script>
export default {
  name: "PrivacyPolicy",
  created() {
    window.scrollTo(0, 0);
  },
};
</script>
